#  Template Go (Golang) build

#  This template allows you to validate your Go (Golang) code.
#  The workflow allows running tests, build and code linting on the default branch.

image: golang:1.22

definitions:
  steps:
    - step: &build
        name: Build
        script:
          - go build .
    - step: &jsmTest
        name: JSM Test
        script:
          - mkdir -p test-reports
          - go install github.com/jstemmer/go-junit-report/v2@latest
          - export ATLASSIAN_OPS_PRODUCT_TYPE="jira-service-desk"
          - go test -v 2>&1 ./... | go-junit-report -set-exit-code > test-reports/report-jsm.xml
        artifacts: # defining the artifacts to be passed to each future step.
          - test-reports/**
          - reports/*.txt
    - step: &compassTest
        name: Compass Test
        script:
          - mkdir -p test-reports
          - go install github.com/jstemmer/go-junit-report/v2@latest
          - export ATLASSIAN_OPS_PRODUCT_TYPE="compass"
          - go test -v 2>&1 ./... | go-junit-report -set-exit-code > test-reports/report-compass.xml
        artifacts: # defining the artifacts to be passed to each future step.
          - test-reports/**
          - reports/*.txt
    - step: &lint
        name: Lint code
        image: golangci/golangci-lint:v1.31.0
        script:
          - golangci-lint run -v
    - step: &replicate-to-github
        name: Replicate main branch to GitHub
        script:
          - git fetch --unshallow && git checkout main && git pull
          - git remote rename origin bitbucket
          - git remote add origin git@github.com:atlassian/terraform-provider-atlassian-operations.git
          - git pull --rebase
          - git checkout -b release-from-bitbucket
          - git push --set-upstream origin release-from-bitbucket --force

pipelines:
  default:
    - parallel:
        - step: *build
  custom:
    replicate-to-github:
        - step: *replicate-to-github
  pull-requests:
    '**':
      - step: *jsmTest
      - step: *compassTest
#     - step: *lint
